### ISSUE TITLE
IJulia is broken

### ISSUE THREAD

**Issue by davidanthoff** [davidanthoff/winjulia#2]
The current version breaks IJulia. The reason is this: any app installed with an MSIX installer runs in a container, and in that container `%APPDATA%` and the registry is virtualized away, so that these become per-app state that is not shared with any other app (the situation is slightly more nuanced than this, but for our case this is an accurate enough description. See [here](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-behind-the-scenes) for the full description). When IJulia.jl writes the kernel information into `%APPDATA%\jupyter` it succeeds, but those files are not visible to any other application than Julia itself. In particular, these files are not visible to Jupyter or Python, and then nothing works.

I've picked IJulia.jl as the example here, but this might be a problem for other packages as well: if they write state into `%APPDATA%` and then rely on other applications to read that state, things won't work.

I consider the IJulia.jl case a showstopper: we obviously need to find some solution to that before we can even consider going forward with the MSIX installer.

Right now I can think of two solutions:
1. We convince the Jupyter project to use different file system locations for configuration files (https://github.com/jupyter/jupyter_client/issues/544). I think that would in general be a good idea, because the Windows Store distributed version of Python seems to be running into similar issues, and any other kernel that wants to ship via the Windows Store would also face the same problem. I think medium to long term, `%APPDATA%` just doesn't seem to be a great place to share cross-application configuration. Having said that, any such change would take a long time to make its way through the Jupyter ecosystem, so I'm not really convinced this would allow us to use an MSIX installer anytime soon.
2. We try to convince MS to give us `unvirtualizedResources` capabilities for a potential Windows Store submission. This would solve the problem entirely: it would just switch off the virtualization of the `%APPDATA%` folder for Julia, problem solved. I'm fairly optimistic that this might work: Python has that capability for its Windows Store submission as well, and in general we seem to have a good reason for asking for it. This would also solve any problems that other packages might have around `%APPDATA%` configuration settings. This strategy will _not_ work for any pre Store AppInstaller based solutions, as far as I can tell there is no way to install a MSIX package via AppInstaller with that capability.

**Comment by staticfloat** [comment]
This should be solvable if we installed our own Python.exe and jupyter python packages, right?  As long as it's all within our own container?

**Comment by davidanthoff** [comment]
I guess that would be another option, but I think it wouldn't solve the case where someone wants to integrate the Julia kernel into an existing Jupyter installation. For example, I normally install Python on my system, then install jupyterlab via pip and then start jupyterlab just from the command line. And I think we really would want the Julia kernel to show up in that scenario.

I'm somewhat optimistic that we might just get permission to disable the whole virtualization of `%APPDATA%` if we ship via the store. That would certainly be by far the most robust and simplest solution.

**Comment by davidanthoff** [comment]
All works now with the version I got into the store :)
