### ISSUE TITLE
Sys.BINDIR returns an inaccessible path

### ISSUE THREAD

**Issue by davidanthoff** [davidanthoff/winjulia#4]
The Julia app is installed into the folder `C:\Program Files\WindowsApps\Julia-1.4.2_1.0.0.0_x64__m018azp39xxy8` by the MSIX engine, and so `Sys.BINDIR` returns `C:\Program Files\WindowsApps\Julia-1.4.2_1.0.0.0_x64__m018azp39xxy8\Julia\bin`. That folder, though, is inaccessible to any application _other_ than Julia itself (or rather any other binary that is not part of the Julia MSIX installer). So if from within Julia one tries to start `C:\Program Files\WindowsApps\Julia-1.4.2_1.0.0.0_x64__m018azp39xxy8\Julia\bin\julia.exe` it works, but if I try to run that from say a shell or some third party application, it won't work.

One example of a program where this leads to a problem right now is the VS Code extension (*).

The MSIX installer also adds a symbolic link (I think) for `julia.exe` to ` ~\AppData\Local\Microsoft\WindowsApps`, and that is the path one should use to start Julia from outside Julia itself, say from VS Code.

I think fixing this might require some fiddling, but it doesn't look impossible to me.

(*) I do have a fix for the VS Code extension that is simply and easy, just can't merge it right now because we are in feature freeze for Juliacon for the extension.

**Comment by musm** [comment]
Is accessing the exe, disabled from a security standpoint or is this just a bug in how `Sys.BINDIR` generates it's path?

**Comment by davidanthoff** [comment]
I think it is disabled because the MSIX installer wants to keep the option to move files into a separate location etc. I think the "real" installation location is considered an implementation detail, or something like that.
