### ISSUE TITLE
Add channels

### ISSUE THREAD

**Issue by davidanthoff** [davidanthoff/winjulia#6]
Right now one can pick a Julia version specifically by giving a full version number. For example, one can configure the default Julia version to be `1.4.2`. We should add "channels" as alternative ways to pick a Julia version.

Useful channels could be `1.2` (=latest build in the 1.2 series), `1` (=latest build in the 1 series), `latest` (=latest released version), `lts` (=latest LTS release) and maybe `nightly` (=latest nightly build).

One could then specify a channel as a choice, for example one could run `juliaup setdefault 1.4` to make the 1.4 channel the default that gets invoked with `julia`.

For each channel, we would want a user changeable configuration that specifies how this channel will update. Useful values might be `auto` (always automatically update to the current build in this channel), `prompt` (prompt the user when a new version is available in that channel to update) and `never` (don't even tell the user about any new versions in the channel).

A good default out-of-the-box configuration might be `latest` as the default channel, with an update setting of `prompt`.

**Comment by davidanthoff** [comment]
A good command to add would also be `juliaup update <channelname>` to update that particular channel to the latest version.

**Comment by musm** [comment]
Is this the general idea:


--
Named Channels:

lts  (latest lts release)
latest (latest stable release)
beta (latest beta/rc builds?)
nightly (nightly builds)

--
Numbered Channels:
1.x
1.1.x
.
.
.
1.12.x
2.x


x is used to denote how the channel gets upated

--
`juliaup update`  with no argument, updates to the latest  release of the last selected channel.

-
For numbered channels

`julia update 1.2` updates to e.g. `1.2.23` i.e. patch 23 (if that exists)
`julia update 1` updates the minor to the latest minor release

**Comment by musm** [comment]
How do we deal with 32 bit versions as well? I used to run them concurrent to test bugs etc. Just some food for thought, probably not super necessary in a   beta release.  We can also not focus on them for now.

**Comment by davidanthoff** [comment]
Yes, exactly! I would probably name the numbered channels just `1`, `1.1`, `1.12`, `2` etc. in the UI? And then the idea would be that any semver part that is _not_ part of the channel name gets updated in that channel.

Another idea I had was that we could add a `source` channel that is a bit special, in that one can configure it to point to a specific location on one's system. That would allow a user to quickly and easily switch the system `julia` command between released versions and a local source build.

> `juliaup update` with no argument, updates to the latest release of the last selected channel.

Yes, updating the default seems the best idea.

> How do we deal with 32 bit versions as well?

See https://github.com/davidanthoff/winjulia/issues/7, I think we just need more channels.

**Comment by davidanthoff** [comment]
Channels are now implemented. There are still some improvements we could work on, I've opened more targeted individual issues for those.

**Comment by omendezmorales** [comment]
Out of my ignrance: Is there a way to remove a channel? I ask since I created a channel in the wrong way, and when I do it in the _[right way](https://github.com/JuliaLang/juliaup/issues/96#issuecomment-1480110471)_, I get the error message:
`Error: Channel name `nightly` is already used.`
Thanks for the help.

**Comment by davidanthoff** [comment]
No, never manually edit that file :) `juliaup remove nightly` should do the trick?
